### ISSUE TITLE
Dockerfile build fails if keys is empty

### ISSUE THREAD

**Issue by kontakt** [tomdotorg/docker-weewx#1]
If there is no content in the keys directory, 

> ONBUILD ADD keys/* /root/.ssh/

 fails with 

> ADD failed: no source files were specified

but will succeed with a dummy file placed in the folder.

**Comment by tomdotorg** [comment]
Thanks for reporting. Is this something you like like to fix? To have fixed? Or is the workaround sufficient?

**Comment by kontakt** [comment]
A fix would be ideal, but my main goals in reporting this issue are providing a record for anyone else who encounters this issue and informing the community that it exists.

The workaround is sufficient for my purposes.

**Comment by tomdotorg** [comment]
I will look into this now. Sorry for the huge delay!

**Comment by tomdotorg** [comment]
There is this text in the README. Do you think this is sufficient of should we change it?

`Make a keys directory at the root of your working directory (where Dockerfile is). This is where you will store the public keys to be used for rsync. The content of this directory will be copied to /root/.ssh/ and will allow weewx to copy your web content to another box. You need this even if you do not plan to use rsync (but it can be an empty directory).`
