### ISSUE TITLE
Adding extensions

### ISSUE THREAD

**Issue by mattster98** [tomdotorg/docker-weewx#6]
I've gone round and round trying to figure out how to add extensions to this image.  I'm probably just going about it the wrong way (connecting via shell to this while running, and using wee_extension, etc).  What would you say is the most straightforward way to add an extension?

**Comment by tomdotorg** [comment]
Sorry for the delay. I have to turn on notifications! I do it by creating images that extend from this base image. Here is an example Dockerfile:

```
FROM mitct02/weewx:5.0.0-1

USER root

ADD . $WEEWX_ROOT/

RUN mkdir -p /home/weewx/.ssh && chown -R weewx:weewx /home/weewx/.ssh
RUN cp $WEEWX_ROOT/keys/* /home/weewx/.ssh/
RUN chmod -R 700 /home/weewx/.ssh/
RUN touch /var/log/weewx.log && chown weewx:weewx /var/log/weewx.log
RUN chown -R weewx:weewx /home/weewx/

WORKDIR $WEEWX_ROOT

USER weewx

RUN /usr/bin/weectl extension install -y $WEEWX_ROOT/extensions/WeeWX-MQTTSubscribe-2.2.2.zip

```
